package iwvg.prac2;

public enum Pile {
	DECK_OF_CARDS,
	DISCARD,
	SUITPILE_OF_SPADES,
	SUITPILE_OF_HEARTS,
	SUITPILE_OF_DIAMONDS,
	SUITPILE_OF_CLUBS,
	STRAIGHT_ONE,
	STRAIGHT_TWO,
	STRAIGHT_THREE,
	STRAIGHT_FOUR,
	STRAIGHT_FIVE,
	STRAIGHT_SIX,
	STRAIGHT_SEVEN
}
