package iwvg.prac2.utils;

public enum Option {
	START,
	MOVE_DECK_TO_DISCARD,
	MOVE_DISCARD_TO_DECK,
	MOVE_DISCARD_TO_SUIT,
	MOVE_DISCARD_TO_STRAIGHT,
	MOVE_STRAIGHT_TO_SUIT,
	MOVE_STRAIGHT_TO_STRAIGHT,
	MOVE_SUIT_TO_STRAIGHT,
	TURN_OVER,
	CONTINUE,
	EXIT,
	EXIT_ALL;
}
